apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: {{ include "dotnetgigs.namespace" . }}
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  rabbitmq.conf: |
    loopback_users.guest = false
