apiVersion: v1
kind: Secret
metadata:
  name: dotnetgigs-secrets
  namespace: {{ include "dotnetgigs.namespace" . }}
  labels:
    {{- include "dotnetgigs.labels" . | nindent 4 }}
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: {{ .Values.secrets.sqlSaPassword | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.secrets.rabbitmqDefaultUser | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.rabbitmqDefaultPass | quote }}
  ApplicantsConnectionString: {{ .Values.secrets.applicantsConnectionString | quote }}
  JobsConnectionString: {{ .Values.secrets.jobsConnectionString | quote }}
