apiVersion: v1
kind: Service
metadata:
  name: hello-api
  labels:
    app.kubernetes.io/name: hello-api
    app.kubernetes.io/part-of: m2cloud-platform
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: hello-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
