apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.component_id }}
  labels:
    app.kubernetes.io/name: ${{ values.component_id }}
    app.kubernetes.io/part-of: m2cloud-platform
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{ values.component_id }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${{ values.component_id }}
        app.kubernetes.io/part-of: m2cloud-platform
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ${{ values.component_id }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: ${{ values.port }}
          env:
            - name: PORT
              value: "${{ values.port }}"
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
