{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${{ values.component_id }}
  namespace: {{ .Values.serviceMonitor.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{ values.component_id }}
  namespaceSelector:
    matchNames:
      - ${{ values.namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
